/*1 EJERCICIO*/
SELECT APELLIDO, DEPT_NO,OFICIO, EMP_NO
FROM EMPLE
WHERE DEPT_NO = 20
AND UPPER(OFICIO)= 'ANALISTA'
ORDER BY APELLIDO,EMP_NO DESC ;

/*2 EJERCICIO*/
SELECT APELLIDO,OFICIO,FECHA_ALT
FROM EMPLE
WHERE FECHA_ALT BETWEEN TO_DATE('01/04/1981','DD/MM/YYYY') AND TO_DATE('30/10/1981','DD/MM/YYYY')
ORDER BY FECHA_ALT;

/*3 EJERCICIO*/
SELECT APELLIDO || ', ' || OFICIO AS "EMPLE, OFI"
FROM EMPLE
ORDER BY APELLIDO;